# Generated by Django 6.0.5 on 2026-05-18 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('experience_required', models.IntegerField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.recruiter')),
            ],
        ),
    ]
