"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { BriefcaseBusiness, ChevronLeft, ChevronRight, MapPin, Pencil, Plus, X } from "lucide-react";
import ProtectedRoute from "@/components/ProtectedRoute";
import Sidebar from "@/components/Sidebar";
import WorkspaceHero from "@/components/WorkspaceHero";
import api from "@/services/api";
import { useToastStore } from "@/store/toastStore";
import type { Experience, Job, JobType, PaginatedJobs, SalaryPeriod } from "@/types";

type JobForm = Omit<Job, "id" | "created_at">;
const emptyJob: JobForm = { is_open: true, title: "", company_name: "", location: "", description: "", requirements: "", salary: 0, salary_period: "year", job_type: "full_time", experience: "fresher" };
const labels: Record<JobType, string> = { full_time: "Full time", part_time: "Part time", internship: "Internship", contract: "Contract" };
const experienceLabels: Record<Experience, string> = { fresher: "Fresher (0 years)", "1_2": "1–2 years", "3_5": "3–5 years", "6_9": "6–9 years", "10_plus": "10+ years" };
const salaryPeriodLabels: Record<SalaryPeriod, string> = { hour: "per hour", day: "per day", week: "per week", month: "per month", year: "per year" };
const salaryText = (job: Job) => `${job.salary.toLocaleString()} ${salaryPeriodLabels[job.salary_period]}`;

function RecruiterJobsContent() {
  const [jobs, setJobs] = useState<Job[]>([]), [page, setPage] = useState(1), [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true), [selected, setSelected] = useState<Job | null>(null), [editing, setEditing] = useState(false), [saving, setSaving] = useState(false);
  const [form, setForm] = useState<JobForm>(emptyJob); const addToast = useToastStore((state) => state.addToast); const pages = Math.max(1, Math.ceil(total / 10));
  const load = useCallback(async () => { setLoading(true); try { const { data } = await api.get<PaginatedJobs>("/recruiter/jobs/", { params: { page } }); setJobs(data.results); setTotal(data.count); } catch { addToast("Unable to load your jobs.", "error"); } finally { setLoading(false); } }, [addToast, page]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const create = () => { setSelected(null); setForm(emptyJob); setEditing(true); };
  const showJob = (job: Job) => { setSelected(job); setForm(job); setEditing(false); };
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); try { const { data } = selected ? await api.patch<Job>(`/recruiter/jobs/${selected.id}/`, form) : await api.post<Job>("/recruiter/jobs/", form); setJobs((items) => selected ? items.map((job) => job.id === data.id ? data : job) : [data, ...items].slice(0, 10)); setTotal((count) => selected ? count : count + 1); setSelected(data); setForm(data); setEditing(false); addToast(selected ? "Job updated successfully." : "Job created successfully.", "success"); } catch { addToast("Unable to save this job. Check all fields and try again.", "error"); } finally { setSaving(false); } };
  const closeOpening = async () => { if (!selected) return; setSaving(true); try { const { data } = await api.patch<Job>(`/recruiter/jobs/${selected.id}/close/`); setJobs((items) => items.map((job) => job.id === data.id ? data : job)); setSelected(data); addToast("Job opening closed. It is no longer visible to candidates.", "success"); } catch { addToast("Unable to close this job opening.", "error"); } finally { setSaving(false); } };
  return <div className="workspace-page flex"><Sidebar /><main className="workspace-content flex-1"><WorkspaceHero role="recruiter" view="jobs" /><section className="recruiter-section"><div className="section-heading"><div><p className="section-kicker">OPEN POSITIONS</p><h1>Manage jobs</h1><p>Create, review, and refine every opportunity from one place.</p></div><button onClick={create} className="designer-button"><Plus size={18} />Create new job</button></div>{loading ? <Loader /> : jobs.length === 0 ? <div className="designer-empty"><span><BriefcaseBusiness /></span><h2>No jobs yet</h2><p>Publish your first position and start meeting great candidates.</p><button onClick={create} className="designer-button"><Plus size={17} />Create new job</button></div> : <><div className="job-designer-grid">{jobs.map((job, index) => <button key={job.id} onClick={() => showJob(job)} className="job-designer-card"><div className="job-card-accent">{String(index + 1).padStart(2, "0")}</div><div className="job-card-heading"><div className="job-icon"><BriefcaseBusiness size={20} /></div><span className={`status-badge ${job.is_open ? "status-hired" : "status-rejected"}`}>{job.is_open ? "Open" : "Closed"}</span></div><h2>{job.title}</h2><p className="job-company">{job.company_name}</p><p className="job-location"><MapPin size={15} />{job.location}</p><p className="job-description">{job.description}</p><div className="job-card-footer"><div><span>{labels[job.job_type]}</span><span>{experienceLabels[job.experience]}</span></div><strong>{salaryText(job)}</strong></div></button>)}</div><Pager page={page} pages={pages} total={total} setPage={setPage} /></>}</section></main>{editing && <JobEditor form={form} setForm={setForm} saving={saving} close={() => setEditing(false)} save={save} title={selected ? "Edit job" : "Create new job"} />}{selected && !editing && <JobDetails job={selected} close={() => setSelected(null)} edit={() => setEditing(true)} closeOpening={closeOpening} closing={saving} />}</div>;
}
function JobDetails({ job, close, edit, closeOpening, closing }: { job: Job; close: () => void; edit: () => void; closeOpening: () => void; closing: boolean }) { return <Modal title={job.title} close={close}><p className="text-slate-600">{job.company_name} · {job.location}</p>{!job.is_open && <p className="mt-4 rounded-xl bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700">This job opening is closed and is hidden from candidates.</p>}<section className="mt-6 space-y-5 text-sm leading-6"><div><h3 className="font-semibold">About the role</h3><p className="whitespace-pre-wrap">{job.description}</p></div><div><h3 className="font-semibold">Requirements</h3><p className="whitespace-pre-wrap">{job.requirements}</p></div><p><b>Type:</b> {labels[job.job_type]} &nbsp; <b>Experience:</b> {experienceLabels[job.experience]} &nbsp; <b>Salary:</b> {salaryText(job)}</p></section><div className="mt-7 flex flex-wrap gap-3"><button onClick={edit} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-medium text-white"><Pencil size={16} /> Edit job</button>{job.is_open && <button disabled={closing} onClick={closeOpening} className="rounded-xl border border-rose-300 px-4 py-2.5 text-sm font-medium text-rose-700 disabled:opacity-50">{closing ? "Closing…" : "Close opening"}</button>}</div></Modal>; }
function JobEditor({ form, setForm, saving, close, save, title }: { form: JobForm; setForm: (form: JobForm) => void; saving: boolean; close: () => void; save: (event: FormEvent<HTMLFormElement>) => void; title: string }) { const input = "rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-slate-900"; const field = (key: "title" | "company_name" | "location", label: string) => <label className="grid gap-2 text-sm font-medium">{label}<input required value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className={input} /></label>; const textField = (key: "description" | "requirements", label: string) => <label className="grid gap-2 text-sm font-medium sm:col-span-2">{label}<textarea required rows={4} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className={input} /></label>; return <Modal title={title} close={close}><form onSubmit={save} className="mt-5 grid gap-4 sm:grid-cols-2">{field("title", "Job title")}{field("company_name", "Company name")}{field("location", "Location")}<label className="grid gap-2 text-sm font-medium">Experience<select value={form.experience} onChange={(e) => setForm({ ...form, experience: e.target.value as Experience })} className={input}>{Object.entries(experienceLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Salary<input required min="0" step="1" type="number" value={form.salary || ""} onChange={(e) => setForm({ ...form, salary: Number(e.target.value) })} className={input} /></label><label className="grid gap-2 text-sm font-medium">Salary period<select value={form.salary_period} onChange={(e) => setForm({ ...form, salary_period: e.target.value as SalaryPeriod })} className={input}>{Object.entries(salaryPeriodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Job type<select value={form.job_type} onChange={(e) => setForm({ ...form, job_type: e.target.value as JobType })} className={input}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{textField("description", "Description")}{textField("requirements", "Requirements")}<div className="flex justify-end gap-3 sm:col-span-2"><button type="button" onClick={close} className="rounded-xl px-4 py-2.5">Cancel</button><button disabled={saving} className="rounded-xl bg-slate-900 px-5 py-2.5 font-medium text-white disabled:opacity-60">{saving ? "Saving…" : "Save job"}</button></div></form></Modal>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="designer-backdrop" role="dialog" aria-modal="true"><div className="designer-modal job-modal"><div className="modal-title-row"><div><p className="section-kicker">JOB DETAILS</p><h2>{title}</h2></div><button onClick={close} className="modal-close" aria-label="Close"><X size={20} /></button></div>{children}</div></div>; }
function Loader() { return <div className="flex justify-center py-20"><div className="h-8 w-8 animate-spin rounded-full border-4 border-slate-200 border-t-slate-900" /></div>; }
function Pager({ page, pages, total, setPage }: { page: number; pages: number; total: number; setPage: (value: number | ((value: number) => number)) => void }) { return <div className="mt-6 flex items-center justify-between border-t border-slate-100 pt-5"><p className="text-sm text-slate-600">{total} jobs · Page {page} of {pages}</p><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronLeft size={18} /></button><button disabled={page === pages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border p-2 disabled:opacity-40"><ChevronRight size={18} /></button></div></div>; }
export default function RecruiterJobsPage() { return <ProtectedRoute requiredRole="recruiter"><RecruiterJobsContent /></ProtectedRoute>; }
